# Importing neccessary libraries

In [1]:
import pandas as pd
import numpy as np

In [2]:
fifa = pd.read_csv('/kaggle/input/fifa-21-messy-raw-dataset-for-cleaning-exploring/fifa21_opensource.csv',
                  low_memory=False)

In [3]:
fifa.head()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [4]:
fifa.tail()

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,\n\n\n\nChongqing Dangdai Lifan FC SWM Team\n2...,...,Low,Low,1 ★,58,23,26,27,50,48,\n2
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,70,46,40,53,16,40,\n3
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,\n\n\n\nWuhan Zall\n2018 ~ 2022\n\n,...,Medium,Medium,1 ★,64,28,26,38,48,51,\n3
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,\n\n\n\nOldham Athletic\n2020 ~ 2021\n\n,...,Medium,Medium,1 ★,64,40,48,49,35,45,\n5
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,\n\n\n\nClub Bolívar\n2020 ~ 2024\n\n,...,Medium,Medium,1 ★,57,32,43,48,44,49,\n2

In [5]:
fifa.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [6]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18979 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18979 non-null  object
 1   LongName          18979 non-null  object
 2   playerUrl         18979 non-null  object
 3   Nationality       18979 non-null  object
 4   Positions         18979 non-null  object
 5   Name              18979 non-null  object
 6   Age               18979 non-null  int64
 7   ↓OVA              18979 non-null  int64
 8   POT               18979 non-null  int64
 9   Team & Contract   18979 non-null  object
 10  ID                18979 non-null  int64
 11  Height            18979 non-null  object
 12  Weight            18979 non-null  object
 13  foot              18979 non-null  object
 14  BOV               18979 non-null  int64
 15  BP                18979 non-null  object
 16  Growth            18979 non-null  int64
 17  Joined            18979 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18979 non-null  object
 20  Wage              18979 non-null  object
 21  Release Clause    18979 non-null  object
 22  Attacking         18979 non-null  int64
 23  Crossing          18979 non-null  int64
 24  Finishing         18979 non-null  int64
 25  Heading Accuracy  18979 non-null  int64
 26  Short Passing     18979 non-null  int64
 27  Volleys           18979 non-null  int64
 28  Skill             18979 non-null  int64
 29  Dribbling         18979 non-null  int64
 30  Curve             18979 non-null  int64
 31  FK Accuracy       18979 non-null  int64
 32  Long Passing      18979 non-null  int64
 33  Ball Control      18979 non-null  int64
 34  Movement          18979 non-null  int64
 35  Acceleration      18979 non-null  int64
 36  Sprint Speed      18979 non-null  int64
 37  Agility           18979 non-null  int64
 38  Reactions         18979 non-null  int64
 39  Balance           18979 non-null  int64
 40  Power             18979 non-null  int64
 41  Shot Power        18979 non-null  int64
 42  Jumping           18979 non-null  int64
 43  Stamina           18979 non-null  int64
 44  Strength          18979 non-null  int64
 45  Long Shots        18979 non-null  int64
 46  Mentality         18979 non-null  int64
 47  Aggression        18979 non-null  int64
 48  Interceptions     18979 non-null  int64
 49  Positioning       18979 non-null  int64
 50  Vision            18979 non-null  int64
 51  Penalties         18979 non-null  int64
 52  Composure         18979 non-null  int64
 53  Defending         18979 non-null  int64
 54  Marking           18979 non-null  int64
 55  Standing Tackle   18979 non-null  int64
 56  Sliding Tackle    18979 non-null  int64
 57  Goalkeeping       18979 non-null  int64
 58  GK Diving         18979 non-null  int64
 59  GK Handling       18979 non-null  int64
 60  GK Kicking        18979 non-null  int64
 61  GK Positioning    18979 non-null  int64
 62  GK Reflexes       18979 non-null  int64
 63  Total Stats       18979 non-null  int64
 64  Base Stats        18979 non-null  int64
 65  W/F               18979 non-null  object
 66  SM                18979 non-null  object
 67  A/W               18979 non-null  object
 68  D/W               18979 non-null  object
 69  IR                18979 non-null  object
 70  PAC               18979 non-null  int64
 71  SHO               18979 non-null  int64
 72  PAS               18979 non-null  int64
 73  DRI               18979 non-null  int64
 74  DEF               18979 non-null  int64
 75  PHY               18979 non-null  int64
 76  Hits              18979 non-null  object
dtypes: int64(55), object(22)
memory usage: 11.1+ MB

## Dealing with duplicates

In [7]:
fifa.duplicated().sum()

1

In [8]:
fifa.drop_duplicates(inplace = True)

## Dealing with non-values

In [9]:
fifa.isna().sum().sort_values(ascending = False)

Loan Date End       17965
photoUrl                0
GK Diving               0
Sliding Tackle          0
Standing Tackle         0
                    ...
Heading Accuracy        0
Finishing               0
Crossing                0
Attacking               0
Hits                    0
Length: 77, dtype: int64

As shown we can't deal with **Loan Date End** Column ,Becaue we can't suggest a patter for this column to fillna , And surly we can't drop nan values of it **because its numbers!**

## Converting Height Column from Feet,in To Cm

In [10]:
def converting_to_cm (x):
    feet, inch = x.split("'")
    inch = inch.replace('"','')
    total_feet = float(feet) + float(inch) * 0.08
    return total_feet * 30.48
fifa['Height'] = fifa['Height'].apply(lambda x : converting_to_cm(x))
# df['Height']

In [11]:
fifa['Height'].round(0)

0        169.0
1        188.0
2        188.0
3        179.0
4        174.0
         ...
18974    177.0
18975    169.0
18976    177.0
18977    174.0
18978    174.0
Name: Height, Length: 18978, dtype: float64

## Is there a problem in Weight column?

In [12]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18978 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18978 non-null  object
 1   LongName          18978 non-null  object
 2   playerUrl         18978 non-null  object
 3   Nationality       18978 non-null  object
 4   Positions         18978 non-null  object
 5   Name              18978 non-null  object
 6   Age               18978 non-null  int64
 7   ↓OVA              18978 non-null  int64
 8   POT               18978 non-null  int64
 9   Team & Contract   18978 non-null  object
 10  ID                18978 non-null  int64
 11  Height            18978 non-null  float64
 12  Weight            18978 non-null  object
 13  foot              18978 non-null  object
 14  BOV               18978 non-null  int64
 15  BP                18978 non-null  object
 16  Growth            18978 non-null  int64
 17  Joined            18978 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18978 non-null  object
 20  Wage              18978 non-null  object
 21  Release Clause    18978 non-null  object
 22  Attacking         18978 non-null  int64
 23  Crossing          18978 non-null  int64
 24  Finishing         18978 non-null  int64
 25  Heading Accuracy  18978 non-null  int64
 26  Short Passing     18978 non-null  int64
 27  Volleys           18978 non-null  int64
 28  Skill             18978 non-null  int64
 29  Dribbling         18978 non-null  int64
 30  Curve             18978 non-null  int64
 31  FK Accuracy       18978 non-null  int64
 32  Long Passing      18978 non-null  int64
 33  Ball Control      18978 non-null  int64
 34  Movement          18978 non-null  int64
 35  Acceleration      18978 non-null  int64
 36  Sprint Speed      18978 non-null  int64
 37  Agility           18978 non-null  int64
 38  Reactions         18978 non-null  int64
 39  Balance           18978 non-null  int64
 40  Power             18978 non-null  int64
 41  Shot Power        18978 non-null  int64
 42  Jumping           18978 non-null  int64
 43  Stamina           18978 non-null  int64
 44  Strength          18978 non-null  int64
 45  Long Shots        18978 non-null  int64
 46  Mentality         18978 non-null  int64
 47  Aggression        18978 non-null  int64
 48  Interceptions     18978 non-null  int64
 49  Positioning       18978 non-null  int64
 50  Vision            18978 non-null  int64
 51  Penalties         18978 non-null  int64
 52  Composure         18978 non-null  int64
 53  Defending         18978 non-null  int64
 54  Marking           18978 non-null  int64
 55  Standing Tackle   18978 non-null  int64
 56  Sliding Tackle    18978 non-null  int64
 57  Goalkeeping       18978 non-null  int64
 58  GK Diving         18978 non-null  int64
 59  GK Handling       18978 non-null  int64
 60  GK Kicking        18978 non-null  int64
 61  GK Positioning    18978 non-null  int64
 62  GK Reflexes       18978 non-null  int64
 63  Total Stats       18978 non-null  int64
 64  Base Stats        18978 non-null  int64
 65  W/F               18978 non-null  object
 66  SM                18978 non-null  object
 67  A/W               18978 non-null  object
 68  D/W               18978 non-null  object
 69  IR                18978 non-null  object
 70  PAC               18978 non-null  int64
 71  SHO               18978 non-null  int64
 72  PAS               18978 non-null  int64
 73  DRI               18978 non-null  int64
 74  DEF               18978 non-null  int64
 75  PHY               18978 non-null  int64
 76  Hits              18978 non-null  object
dtypes: float64(1), int64(55), object(21)
memory usage: 11.3+ MB

In [13]:
fifa['Weight'] = fifa['Weight'].str.replace('lbs','').astype(np.float32)

In [14]:
fifa['Weight']

0        159.0
1        183.0
2        192.0
3        154.0
4        150.0
         ...
18974    154.0
18975    128.0
18976    146.0
18977    143.0
18978    150.0
Name: Weight, Length: 18978, dtype: float32

## Remove any newline in each object column

In [15]:
for column in fifa.columns:
    if fifa[column].dtype == np.object_:
        fifa[column] = fifa[column].str.replace('\n','')

## Expanding Value, Wage and Release Clause To its currency value, With take in care the ('M','K') Value difference

In [16]:
fifa.info()

<class 'pandas.core.frame.DataFrame'>
Index: 18978 entries, 0 to 18978
Data columns (total 77 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   photoUrl          18978 non-null  object
 1   LongName          18978 non-null  object
 2   playerUrl         18978 non-null  object
 3   Nationality       18978 non-null  object
 4   Positions         18978 non-null  object
 5   Name              18978 non-null  object
 6   Age               18978 non-null  int64
 7   ↓OVA              18978 non-null  int64
 8   POT               18978 non-null  int64
 9   Team & Contract   18978 non-null  object
 10  ID                18978 non-null  int64
 11  Height            18978 non-null  float64
 12  Weight            18978 non-null  float32
 13  foot              18978 non-null  object
 14  BOV               18978 non-null  int64
 15  BP                18978 non-null  object
 16  Growth            18978 non-null  int64
 17  Joined            18978 non-null  object
 18  Loan Date End     1013 non-null   object
 19  Value             18978 non-null  object
 20  Wage              18978 non-null  object
 21  Release Clause    18978 non-null  object
 22  Attacking         18978 non-null  int64
 23  Crossing          18978 non-null  int64
 24  Finishing         18978 non-null  int64
 25  Heading Accuracy  18978 non-null  int64
 26  Short Passing     18978 non-null  int64
 27  Volleys           18978 non-null  int64
 28  Skill             18978 non-null  int64
 29  Dribbling         18978 non-null  int64
 30  Curve             18978 non-null  int64
 31  FK Accuracy       18978 non-null  int64
 32  Long Passing      18978 non-null  int64
 33  Ball Control      18978 non-null  int64
 34  Movement          18978 non-null  int64
 35  Acceleration      18978 non-null  int64
 36  Sprint Speed      18978 non-null  int64
 37  Agility           18978 non-null  int64
 38  Reactions         18978 non-null  int64
 39  Balance           18978 non-null  int64
 40  Power             18978 non-null  int64
 41  Shot Power        18978 non-null  int64
 42  Jumping           18978 non-null  int64
 43  Stamina           18978 non-null  int64
 44  Strength          18978 non-null  int64
 45  Long Shots        18978 non-null  int64
 46  Mentality         18978 non-null  int64
 47  Aggression        18978 non-null  int64
 48  Interceptions     18978 non-null  int64
 49  Positioning       18978 non-null  int64
 50  Vision            18978 non-null  int64
 51  Penalties         18978 non-null  int64
 52  Composure         18978 non-null  int64
 53  Defending         18978 non-null  int64
 54  Marking           18978 non-null  int64
 55  Standing Tackle   18978 non-null  int64
 56  Sliding Tackle    18978 non-null  int64
 57  Goalkeeping       18978 non-null  int64
 58  GK Diving         18978 non-null  int64
 59  GK Handling       18978 non-null  int64
 60  GK Kicking        18978 non-null  int64
 61  GK Positioning    18978 non-null  int64
 62  GK Reflexes       18978 non-null  int64
 63  Total Stats       18978 non-null  int64
 64  Base Stats        18978 non-null  int64
 65  W/F               18978 non-null  object
 66  SM                18978 non-null  object
 67  A/W               18978 non-null  object
 68  D/W               18978 non-null  object
 69  IR                18978 non-null  object
 70  PAC               18978 non-null  int64
 71  SHO               18978 non-null  int64
 72  PAS               18978 non-null  int64
 73  DRI               18978 non-null  int64
 74  DEF               18978 non-null  int64
 75  PHY               18978 non-null  int64
 76  Hits              18978 non-null  object
dtypes: float32(1), float64(1), int64(55), object(20)
memory usage: 11.2+ MB

In [17]:
fifa['Value']

0        €67.5M
1          €46M
2          €75M
3          €87M
4          €90M
          ...
18974      €35K
18975      €60K
18976      €40K
18977      €60K
18978      €60K
Name: Value, Length: 18978, dtype: object

First we need to make sure that all values are in **Euro Currency**

In [18]:
fifa['Value'].str[0].value_counts()

Value
€    18978
Name: count, dtype: int64

In [19]:
fifa['Value'] = fifa['Value'].str.replace("€",'')

In [20]:
# Slicing the Million values to start work on its
Mill_Ser_Value = fifa.loc[fifa['Value'].str.contains('M'),'Value']

In [21]:
Mill_Ser_Value = Mill_Ser_Value.str.replace('M','').astype(np.float32) * 1000000

In [22]:
fifa.loc[fifa['Value'].str.contains('M'),'Value'] = Mill_Ser_Value

In [23]:
# Slicing the Thousand values to start work on its
Thous_Ser_Value = fifa.loc[fifa['Value'].str.contains('K') == True,'Value']

In [24]:
Thous_Ser_Value = Thous_Ser_Value.str.replace('K','').astype(np.float32) * 1000

In [25]:
fifa.loc[fifa['Value'].str.contains('K') == True,'Value'] = Thous_Ser_Value

In [26]:
fifa['Value']

0        67500000.0
1        46000000.0
2        75000000.0
3        87000000.0
4        90000000.0
            ...
18974       35000.0
18975       60000.0
18976       40000.0
18977       60000.0
18978       60000.0
Name: Value, Length: 18978, dtype: object

we can make it actually also by **apply** :

In [27]:
fifa['Wage'] = fifa['Wage'].str.replace('€','')

In [28]:
def change_cur(x):
    if 'M' in x:
        x = float(x.replace('M',''))
        return x * 1000000
    elif 'K' in x:
        x = float(x.replace('K',''))
        return x * 1000
    return x
fifa['Wage'] = fifa['Wage'].apply(change_cur)

In [29]:
fifa['Wage']

0        560000.0
1        220000.0
2        125000.0
3        370000.0
4        270000.0
           ...
18974      1000.0
18975         500
18976      1000.0
18977         500
18978         500
Name: Wage, Length: 18978, dtype: object

In [30]:
fifa['Release Clause'] = fifa['Release Clause'].str.replace('€','')

In [31]:
fifa['Release Clause'] = fifa['Release Clause'].apply(change_cur)

In [32]:
fifa['Release Clause']

0        138400000.0
1         75900000.0
2        159400000.0
3        161000000.0
4        166500000.0
            ...
18974        57000.0
18975       165000.0
18976        70000.0
18977       165000.0
18978       167000.0
Name: Release Clause, Length: 18978, dtype: object

## Split Team and Contract

In [33]:
fifa['Contract'] = fifa['Team & Contract'].str.findall(r'[\d~ ]+').str[-1]

In [34]:
def get_name_club(x):
    name_club = ''
    for letter in x:
        if letter in ['1','2']:
            return name_club
        else:
            name_club += letter
        
fifa['Team'] = fifa['Team & Contract'].apply(get_name_club)

In [35]:
#drop colum
fifa.drop(columns = ['Team & Contract'], inplace = True)

In [36]:
fifa

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,ID,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract,Team
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,158023,...,5 ★,85,92,91,95,38,65,372,2004 ~ 2021,FC Barcelona
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,20801,...,5 ★,89,93,81,89,35,77,344,2018 ~ 2022,Juventus
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,200389,...,3 ★,87,92,78,90,52,90,86,2014 ~ 2023,Atlético Madrid
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,192985,...,4 ★,76,86,93,88,64,78,163,2015 ~ 2023,Manchester City
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,190871,...,5 ★,91,85,86,94,36,59,273,2017 ~ 2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,Zhang Mengxuan,21,47,52,257710,...,1 ★,58,23,26,27,50,48,2,2020 ~ 2020,Chongqing Dangdai Lifan FC SWM Team
18975,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,V. Da Silva,17,47,67,258736,...,1 ★,70,46,40,53,16,40,3,2020 ~ 2021,Oldham Athletic
18976,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,Xia Ao,21,47,55,247223,...,1 ★,64,28,26,38,48,51,3,2018 ~ 2022,Wuhan Zall
18977,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,B. Hough,17,47,67,258760,...,1 ★,64,40,48,49,35,45,5,2020 ~ 2021,Oldham Athletic
18978,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,M. Flores,19,47,63,255958,...,1 ★,57,32,43,48,44,49,2,2020 ~ 2024,Club Bolívar

## Reorgnizing the data to get better View

In [37]:
columns = ['ID','Name','Age'] + [column for column in fifa.columns if not(column in ['ID','Name','Age'])]

In [38]:
fifa = fifa[columns]

In [39]:
fifa

,ID,Name,Age,photoUrl,LongName,playerUrl,Nationality,Positions,↓OVA,POT,...,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,Contract,Team
0,158023,L. Messi,33,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,93,93,...,5 ★,85,92,91,95,38,65,372,2004 ~ 2021,FC Barcelona
1,20801,Cristiano Ronaldo,35,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,92,92,...,5 ★,89,93,81,89,35,77,344,2018 ~ 2022,Juventus
2,200389,J. Oblak,27,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,91,93,...,3 ★,87,92,78,90,52,90,86,2014 ~ 2023,Atlético Madrid
3,192985,K. De Bruyne,29,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,91,91,...,4 ★,76,86,93,88,64,78,163,2015 ~ 2023,Manchester City
4,190871,Neymar Jr,28,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,91,91,...,5 ★,91,85,86,94,36,59,273,2017 ~ 2022,Paris Saint-Germain
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,257710,Zhang Mengxuan,21,https://cdn.sofifa.com/players/257/710/21_60.png,Mengxuan Zhang,http://sofifa.com/player/257710/mengxuan-zhang...,China PR,CB,47,52,...,1 ★,58,23,26,27,50,48,2,2020 ~ 2020,Chongqing Dangdai Lifan FC SWM Team
18975,258736,V. Da Silva,17,https://cdn.sofifa.com/players/258/736/21_60.png,Vani Da Silva,http://sofifa.com/player/258736/vani-da-silva/...,England,ST,47,67,...,1 ★,70,46,40,53,16,40,3,2020 ~ 2021,Oldham Athletic
18976,247223,Xia Ao,21,https://cdn.sofifa.com/players/247/223/21_60.png,Ao Xia,http://sofifa.com/player/247223/ao-xia/210005/,China PR,CB,47,55,...,1 ★,64,28,26,38,48,51,3,2018 ~ 2022,Wuhan Zall
18977,258760,B. Hough,17,https://cdn.sofifa.com/players/258/760/21_60.png,Ben Hough,http://sofifa.com/player/258760/ben-hough/210005/,England,CM,47,67,...,1 ★,64,40,48,49,35,45,5,2020 ~ 2021,Oldham Athletic
18978,255958,M. Flores,19,https://cdn.sofifa.com/players/255/958/21_60.png,Mateo Flores,http://sofifa.com/player/255958/mateo-flores/2...,Bolivia,CDM,47,63,...,1 ★,57,32,43,48,44,49,2,2020 ~ 2024,Club Bolívar